[package]
name = "mdview-html"
version = "0.1.0"
authors = ["Skyler van Boheemen"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
mdview-lexer = { path = "../lexer", version = "0.1.0" }
regex = "1.5.4"
lazy_static = "1.4.0"