[package]
name = "mdview-cli"
version = "0.1.0"
authors = ["Skyler van Boheemen"]
edition = "2018"

[[bin]]
name = "mdview"
path = "main.rs"

[dependencies]
mdview-lexer = {path = "../lexer", version = "0.1.0"}

clap = "2.33.3"
serde_json = "1.0.64"